server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boarddb
      username: root
      password: 1234

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
